//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string AgeRange1 { get; set; }
        public string AgeRange2 { get; set; }
        public string AgeRange3 { get; set; }
        public string Gender { get; set; }
        public string Interest1 { get; set; }
        public string Interest2 { get; set; }
        public string Interest3 { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}
